linters:
  enable-all: true
  fast: false
  disable:
    - varnamelen
    - wsl
  # deprecated
    - structcheck
    - exhaustivestruct
    - ifshort
    - varcheck
    - deadcode
    - nosnakecase
    - scopelint
    - golint
    - interfacer
    - maligned