# cfw goreleaser.yaml file.
# documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    skip: true
archives:
  - name_template: "{{ .ProjectName }}_{{ .VERSION }}"
    format: zip
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
